### ISSUE TITLE
Scrot doesn't override screenshot

### ISSUE THREAD

**Issue by maximelovino** [axelfahy/dotfiles#1]
In script https://github.com/axelfahy/dotfiles/blob/master/i3/.i3/lockscript.sh the `scrot` command is missing a flag to override the screenshot:
https://github.com/axelfahy/dotfiles/blob/3160199d33371425f69c8a3af6af0dbed8d2b69e/i3/.i3/lockscript.sh#L24

should be:
```
scrot -o /tmp/screen_locked.png
```

**Comment by axelfahy** [comment]
That's right, I will correct it. Thanks !
